version: '3'

services:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=builder
      - APP_DB_NAME=builder
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
# docker compose -f docker-compose-local.yml up -d    /up database