#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
CREATE SCHEMA builder;

    CREATE TABLE IF NOT EXISTS builder.certificate (
      id INT NOT NULL PRIMARY KEY,
      name VARCHAR(200) NULL
      );

    CREATE TABLE IF NOT EXISTS builder.user(
      id       INT          GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
      name     VARCHAR(100) NOT NULL,
      password VARCHAR(500) NOT NULL,
      email    VARCHAR(100) UNIQUE NOT NULL,
      role     VARCHAR(30) default 'CUSTOMER',
      status   VARCHAR(30) default 'ACTIVE'
    );

    CREATE TABLE IF NOT EXISTS builder.contract (
      id INT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
      owner_id INT NOT NULL,
      description VARCHAR(500) NOT NULL,
      start_date DATE NOT NULL,
      end_date DATE NOT NULL,
      start_price INT NOT NULL,
        FOREIGN KEY (owner_id) REFERENCES builder.user (id));

    CREATE TABLE IF NOT EXISTS builder.offer
    (
        id             INT GENERATED BY DEFAULT AS IDENTITY not null,
        offer_owner_id INT NOT NULL,
        contract_id    INT,
        price          INT NOT NULL,
        CONSTRAINT pk_offer PRIMARY KEY (id),
        CONSTRAINT fk_offer_owner_id FOREIGN KEY (offer_owner_id) REFERENCES builder.user (id),
        CONSTRAINT fk_contract_id FOREIGN KEY (contract_id) REFERENCES builder.contract (id)
    );

    CREATE TABLE IF NOT EXISTS builder.user_certificate (
      user_id INT NOT NULL,
      certificate_id INT NOT NULL,
      PRIMARY KEY (user_id, certificate_id),
      CONSTRAINT fk_certificate_id FOREIGN KEY (certificate_id) REFERENCES builder.certificate (id),
      CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES builder.user (id));

COMMIT;

INSERT INTO builder.certificate (ID, NAME)
VALUES ('1', 'Filling window and door openings');
INSERT INTO builder.certificate (ID, NAME)
VALUES ('2', 'Installation of external networks and structures');
INSERT INTO builder.certificate (ID, NAME)
VALUES ('3', 'Execution of works on the device of anti-corrosion ' ||
             'coatings of building structures of buildings and structures');
INSERT INTO builder.certificate (ID, NAME)
VALUES ('4', 'Execution of works on the arrangement of road surfaces ' ||
             'of pedestrian zones from sidewalk slabs');
INSERT INTO builder.certificate (ID, NAME)
VALUES ('5', 'Execution of works on the construction of insulating coatings');
INSERT INTO builder.certificate (ID, NAME)
VALUES ('6', 'Execution of work on the arrangement of foundations, ' ||
             'foundations of buildings and structures');
INSERT INTO builder.certificate (ID, NAME)
VALUES ('7', 'Performing work on the installation of thermal insulation ' ||
             'of the enclosing structures of buildings and structures');

INSERT INTO builder.user (NAME, PASSWORD, ROLE, EMAIL)
VALUES ('Customer', '$2a$12$ma0C6gCWmZL/d3FSt78mF.FCcLdfBqc4XXyRrDBv54EbWEPcj3OIC', 'CUSTOMER', 'castomer@gmail.com');
INSERT INTO builder.user (NAME, PASSWORD, ROLE, EMAIL)
VALUES ('SecondCustomer', 'password', 'CUSTOMER', 'secondCastomer@gmail.com');
INSERT INTO builder.user (NAME, PASSWORD, ROLE, EMAIL)
VALUES ('Contractor', '$2a$12$ma0C6gCWmZL/d3FSt78mF.FCcLdfBqc4XXyRrDBv54EbWEPcj3OIC', 'CONTRACTOR',
        'contractor@gmail.com');
INSERT INTO builder.user (NAME, PASSWORD, ROLE, EMAIL)
VALUES ('SecondContractor', 'password', 'CONTRACTOR', 'SecondContractor@gmail.com');
INSERT INTO builder.user (NAME, PASSWORD, ROLE, EMAIL)
VALUES ('Admin', '$2a$12$ma0C6gCWmZL/d3FSt78mF.FCcLdfBqc4XXyRrDBv54EbWEPcj3OIC', 'ADMIN', 'admin@gmail.com');

INSERT INTO builder.contract (OWNER_ID, DESCRIPTION, START_DATE, END_DATE, START_PRICE)
VALUES ('1', 'first contract', '2022-01-01', '2022-12-31', '28000');
INSERT INTO builder.contract (OWNER_ID, DESCRIPTION, START_DATE, END_DATE, START_PRICE)
VALUES ('2', 'second contract', '2022-03-01', '2022-09-30', '30000');

INSERT INTO builder.offer (OFFER_OWNER_ID, CONTRACT_ID, PRICE)
VALUES ('3', '1', '27500');
INSERT INTO builder.offer (OFFER_OWNER_ID, CONTRACT_ID, PRICE)
VALUES ('4', '1', '26000');

INSERT INTO builder.user_certificate (user_id, certificate_id)
VALUES ('3', '1');
INSERT INTO builder.user_certificate (user_id, certificate_id) VALUES ('3', '6');
INSERT INTO builder.user_certificate (user_id, certificate_id) VALUES ('3', '7');
INSERT INTO builder.user_certificate (user_id, certificate_id) VALUES ('4', '4');
INSERT INTO builder.user_certificate (user_id, certificate_id) VALUES ('4', '5');

COMMIT;
EOSQL