CREATE SCHEMA builder;

CREATE TABLE IF NOT EXISTS builder.certificate (
                                                   id INT NOT NULL PRIMARY KEY,
                                                   name VARCHAR(200) NULL
);

CREATE TABLE IF NOT EXISTS builder.user(
                                           id       INT          GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
                                           name     VARCHAR(100) NOT NULL,
                                           password VARCHAR(500) NOT NULL,
                                           email    VARCHAR(100) UNIQUE NOT NULL,
                                           role     VARCHAR(30) default 'CUSTOMER',
                                           status   VARCHAR(30) default 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS builder.contract (
                                                id INT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
                                                owner_id INT NOT NULL,
                                                description VARCHAR(500) NOT NULL,
                                                start_date DATE NOT NULL,
                                                end_date DATE NOT NULL,
                                                start_price INT NOT NULL,
                                                FOREIGN KEY (owner_id) REFERENCES builder.user (id));

CREATE TABLE IF NOT EXISTS builder.offer
(
    id             INT GENERATED BY DEFAULT AS IDENTITY not null,
    offer_owner_id INT NOT NULL,
    contract_id    INT,
    price          INT NOT NULL,
    CONSTRAINT pk_offer PRIMARY KEY (id),
    CONSTRAINT fk_offer_owner_id FOREIGN KEY (offer_owner_id) REFERENCES builder.user (id),
    CONSTRAINT fk_contract_id FOREIGN KEY (contract_id) REFERENCES builder.contract (id)
);

CREATE TABLE IF NOT EXISTS builder.user_certificate (
                                                        user_id INT NOT NULL,
                                                        certificate_id INT NOT NULL,
                                                        PRIMARY KEY (user_id, certificate_id),
                                                        CONSTRAINT fk_certificate_id FOREIGN KEY (certificate_id) REFERENCES builder.certificate (id),
                                                        CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES builder.user (id));

COMMIT;